import localFont from "next/font/local";
import "./globals.css";
import NextAuthProvider from "@/app/components/nextauthProvider";
import MyMSALProvider from "./msal/msalProvider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "NextJS Auth App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MyMSALProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </MyMSALProvider>
      </body>
    </html>
  );
}
